# Form implementation generated from reading ui file 'ui/settings.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(628, 695)
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(parent=Settings)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.figureBedPath = QtWidgets.QLineEdit(parent=Settings)
        self.figureBedPath.setText("")
        self.figureBedPath.setClearButtonEnabled(True)
        self.figureBedPath.setObjectName("figureBedPath")
        self.horizontalLayout_4.addWidget(self.figureBedPath)
        self.label_7 = QtWidgets.QLabel(parent=Settings)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.figureBedToken = QtWidgets.QLineEdit(parent=Settings)
        self.figureBedToken.setText("")
        self.figureBedToken.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.figureBedToken.setClearButtonEnabled(True)
        self.figureBedToken.setObjectName("figureBedToken")
        self.horizontalLayout_4.addWidget(self.figureBedToken)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_19 = QtWidgets.QLabel(parent=Settings)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_14.addWidget(self.label_19)
        self.videoInfo = QtWidgets.QLineEdit(parent=Settings)
        self.videoInfo.setObjectName("videoInfo")
        self.horizontalLayout_14.addWidget(self.videoInfo)
        self.gridLayout.addLayout(self.horizontalLayout_14, 3, 0, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(parent=Settings)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.screenshotNumber = QtWidgets.QSpinBox(parent=Settings)
        self.screenshotNumber.setMaximum(5)
        self.screenshotNumber.setProperty("value", 1)
        self.screenshotNumber.setObjectName("screenshotNumber")
        self.horizontalLayout_7.addWidget(self.screenshotNumber)
        self.label_2 = QtWidgets.QLabel(parent=Settings)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.screenshotThreshold = QtWidgets.QDoubleSpinBox(parent=Settings)
        self.screenshotThreshold.setDecimals(2)
        self.screenshotThreshold.setMaximum(5.0)
        self.screenshotThreshold.setSingleStep(0.01)
        self.screenshotThreshold.setProperty("value", 0.1)
        self.screenshotThreshold.setObjectName("screenshotThreshold")
        self.horizontalLayout_7.addWidget(self.screenshotThreshold)
        self.gridLayout.addLayout(self.horizontalLayout_7, 4, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(parent=Settings)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.screenshotStart = QtWidgets.QDoubleSpinBox(parent=Settings)
        self.screenshotStart.setDecimals(2)
        self.screenshotStart.setMaximum(1.0)
        self.screenshotStart.setSingleStep(0.01)
        self.screenshotStart.setProperty("value", 0.1)
        self.screenshotStart.setObjectName("screenshotStart")
        self.horizontalLayout_8.addWidget(self.screenshotStart)
        self.label_5 = QtWidgets.QLabel(parent=Settings)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.screenshotEnd = QtWidgets.QDoubleSpinBox(parent=Settings)
        self.screenshotEnd.setDecimals(2)
        self.screenshotEnd.setMaximum(1.0)
        self.screenshotEnd.setSingleStep(0.01)
        self.screenshotEnd.setProperty("value", 0.9)
        self.screenshotEnd.setObjectName("screenshotEnd")
        self.horizontalLayout_8.addWidget(self.screenshotEnd)
        self.gridLayout.addLayout(self.horizontalLayout_8, 5, 0, 1, 2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.autoUploadScreenshot = QtWidgets.QCheckBox(parent=Settings)
        self.autoUploadScreenshot.setChecked(True)
        self.autoUploadScreenshot.setObjectName("autoUploadScreenshot")
        self.horizontalLayout_9.addWidget(self.autoUploadScreenshot)
        self.pasteScreenshotUrl = QtWidgets.QCheckBox(parent=Settings)
        self.pasteScreenshotUrl.setChecked(True)
        self.pasteScreenshotUrl.setObjectName("pasteScreenshotUrl")
        self.horizontalLayout_9.addWidget(self.pasteScreenshotUrl)
        self.deleteScreenshot = QtWidgets.QCheckBox(parent=Settings)
        self.deleteScreenshot.setChecked(True)
        self.deleteScreenshot.setObjectName("deleteScreenshot")
        self.horizontalLayout_9.addWidget(self.deleteScreenshot)
        self.gridLayout.addLayout(self.horizontalLayout_9, 6, 0, 1, 2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.getThumbnails = QtWidgets.QCheckBox(parent=Settings)
        self.getThumbnails.setObjectName("getThumbnails")
        self.horizontalLayout_11.addWidget(self.getThumbnails)
        self.label_13 = QtWidgets.QLabel(parent=Settings)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.rows = QtWidgets.QSpinBox(parent=Settings)
        self.rows.setMinimum(1)
        self.rows.setMaximum(9)
        self.rows.setProperty("value", 4)
        self.rows.setObjectName("rows")
        self.horizontalLayout_11.addWidget(self.rows)
        self.label_8 = QtWidgets.QLabel(parent=Settings)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.cols = QtWidgets.QSpinBox(parent=Settings)
        self.cols.setMinimum(1)
        self.cols.setMaximum(9)
        self.cols.setProperty("value", 4)
        self.cols.setObjectName("cols")
        self.horizontalLayout_11.addWidget(self.cols)
        self.gridLayout.addLayout(self.horizontalLayout_11, 7, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(parent=Settings)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.renameFile = QtWidgets.QCheckBox(parent=Settings)
        self.renameFile.setChecked(False)
        self.renameFile.setObjectName("renameFile")
        self.horizontalLayout_10.addWidget(self.renameFile)
        self.makeDir = QtWidgets.QCheckBox(parent=Settings)
        self.makeDir.setChecked(False)
        self.makeDir.setObjectName("makeDir")
        self.horizontalLayout_10.addWidget(self.makeDir)
        self.gridLayout.addLayout(self.horizontalLayout_10, 8, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_22 = QtWidgets.QLabel(parent=Settings)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_19.addWidget(self.label_22)
        self.qb = QtWidgets.QRadioButton(parent=Settings)
        self.qb.setToolTipDuration(1)
        self.qb.setChecked(False)
        self.qb.setObjectName("qb")
        self.buttonGroup = QtWidgets.QButtonGroup(Settings)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.qb)
        self.horizontalLayout_19.addWidget(self.qb)
        self.tr = QtWidgets.QRadioButton(parent=Settings)
        self.tr.setChecked(True)
        self.tr.setObjectName("tr")
        self.buttonGroup.addButton(self.tr)
        self.horizontalLayout_19.addWidget(self.tr)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.gridLayout.addLayout(self.verticalLayout_2, 9, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(parent=Settings)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.downloaderHost = QtWidgets.QLineEdit(parent=Settings)
        self.downloaderHost.setObjectName("downloaderHost")
        self.horizontalLayout_6.addWidget(self.downloaderHost)
        self.gridLayout.addLayout(self.horizontalLayout_6, 9, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_15 = QtWidgets.QLabel(parent=Settings)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.downloaderUser = QtWidgets.QLineEdit(parent=Settings)
        self.downloaderUser.setObjectName("downloaderUser")
        self.horizontalLayout_5.addWidget(self.downloaderUser)
        self.label_16 = QtWidgets.QLabel(parent=Settings)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.downloaderPass = QtWidgets.QLineEdit(parent=Settings)
        self.downloaderPass.setObjectName("downloaderPass")
        self.horizontalLayout_5.addWidget(self.downloaderPass)
        self.gridLayout.addLayout(self.horizontalLayout_5, 10, 0, 1, 2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_18 = QtWidgets.QLabel(parent=Settings)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.resourcePath = QtWidgets.QLineEdit(parent=Settings)
        self.resourcePath.setObjectName("resourcePath")
        self.horizontalLayout_13.addWidget(self.resourcePath)
        self.gridLayout.addLayout(self.horizontalLayout_13, 11, 0, 1, 2)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_21 = QtWidgets.QLabel(parent=Settings)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_18.addWidget(self.label_21)
        self.proxyUrl = QtWidgets.QLineEdit(parent=Settings)
        self.proxyUrl.setObjectName("proxyUrl")
        self.horizontalLayout_18.addWidget(self.proxyUrl)
        self.gridLayout.addLayout(self.horizontalLayout_18, 12, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_17 = QtWidgets.QLabel(parent=Settings)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.tjuCookie = QtWidgets.QLineEdit(parent=Settings)
        self.tjuCookie.setObjectName("tjuCookie")
        self.horizontalLayout_12.addWidget(self.tjuCookie)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_9 = QtWidgets.QLabel(parent=Settings)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_15.addWidget(self.label_9)
        self.agsvCookie = QtWidgets.QLineEdit(parent=Settings)
        self.agsvCookie.setObjectName("agsvCookie")
        self.horizontalLayout_15.addWidget(self.agsvCookie)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_11 = QtWidgets.QLabel(parent=Settings)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_16.addWidget(self.label_11)
        self.pterCookie = QtWidgets.QLineEdit(parent=Settings)
        self.pterCookie.setObjectName("pterCookie")
        self.horizontalLayout_16.addWidget(self.pterCookie)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_20 = QtWidgets.QLabel(parent=Settings)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_17.addWidget(self.label_20)
        self.kylinCookie = QtWidgets.QLineEdit(parent=Settings)
        self.kylinCookie.setObjectName("kylinCookie")
        self.horizontalLayout_17.addWidget(self.kylinCookie)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.gridLayout.addLayout(self.verticalLayout, 13, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(30, -1, 30, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveButton = QtWidgets.QPushButton(parent=Settings)
        self.saveButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=Settings)
        self.cancelButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.gridLayout.addLayout(self.horizontalLayout, 14, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=Settings)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.screenshotPath = QtWidgets.QLineEdit(parent=Settings)
        self.screenshotPath.setText("")
        self.screenshotPath.setClearButtonEnabled(True)
        self.screenshotPath.setObjectName("screenshotPath")
        self.horizontalLayout_2.addWidget(self.screenshotPath)
        self.selectScreenshotPathButton = QtWidgets.QPushButton(parent=Settings)
        self.selectScreenshotPathButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.selectScreenshotPathButton.setObjectName("selectScreenshotPathButton")
        self.horizontalLayout_2.addWidget(self.selectScreenshotPathButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(parent=Settings)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.torrentPath = QtWidgets.QLineEdit(parent=Settings)
        self.torrentPath.setText("")
        self.torrentPath.setClearButtonEnabled(True)
        self.torrentPath.setObjectName("torrentPath")
        self.horizontalLayout_3.addWidget(self.torrentPath)
        self.selectTorrentPathButton = QtWidgets.QPushButton(parent=Settings)
        self.selectTorrentPathButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.selectTorrentPathButton.setObjectName("selectTorrentPathButton")
        self.horizontalLayout_3.addWidget(self.selectTorrentPathButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "设置"))
        self.label_6.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_6.setText(_translate("Settings", "图床api地址："))
        self.figureBedPath.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_7.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_7.setText(_translate("Settings", "图床api密钥："))
        self.figureBedToken.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_19.setText(_translate("Settings", "短剧信息："))
        self.label.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label.setText(_translate("Settings", "截图数量："))
        self.screenshotNumber.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_2.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_2.setText(_translate("Settings", "关键帧复杂度："))
        self.screenshotThreshold.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_4.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_4.setText(_translate("Settings", "截图起始点（百分比）："))
        self.screenshotStart.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_5.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_5.setText(_translate("Settings", "截图终止点（百分比）："))
        self.screenshotEnd.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.autoUploadScreenshot.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.autoUploadScreenshot.setText(_translate("Settings", "自动上传图床"))
        self.pasteScreenshotUrl.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.pasteScreenshotUrl.setText(_translate("Settings", "将链接粘贴到简介后"))
        self.deleteScreenshot.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.deleteScreenshot.setText(_translate("Settings", "上传后删除本地图片"))
        self.getThumbnails.setText(_translate("Settings", "生成缩略图"))
        self.label_13.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_13.setText(_translate("Settings", "横向数量："))
        self.rows.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_8.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_8.setText(_translate("Settings", "纵向数量："))
        self.cols.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_10.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_10.setText(_translate("Settings", "获取标准命名时："))
        self.renameFile.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.renameFile.setText(_translate("Settings", "自动将文件（文件夹）重命名"))
        self.makeDir.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.makeDir.setText(_translate("Settings", "将文件放入同名文件夹"))
        self.label_22.setText(_translate("Settings", "下载器类型："))
        self.qb.setText(_translate("Settings", "Qb"))
        self.tr.setText(_translate("Settings", "Tr"))
        self.label_14.setText(_translate("Settings", "下载器地址："))
        self.label_15.setText(_translate("Settings", "下载器用户名："))
        self.label_16.setText(_translate("Settings", "下载器密码"))
        self.label_18.setText(_translate("Settings", "做种路径："))
        self.label_21.setText(_translate("Settings", "代理地址:"))
        self.proxyUrl.setPlaceholderText(_translate("Settings", "格式为:http://xxx:7890"))
        self.label_17.setText(_translate("Settings", "tju_cookie："))
        self.label_9.setText(_translate("Settings", "agsv_cookie:"))
        self.label_11.setText(_translate("Settings", "Pter_cookie:"))
        self.label_20.setText(_translate("Settings", "kylin_cookie:"))
        self.saveButton.setText(_translate("Settings", "保存"))
        self.cancelButton.setText(_translate("Settings", "取消"))
        self.label_3.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_3.setText(_translate("Settings", "截图储存地址："))
        self.screenshotPath.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.selectScreenshotPathButton.setText(_translate("Settings", "浏览"))
        self.label_12.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_12.setText(_translate("Settings", "种子储存地址："))
        self.torrentPath.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.selectTorrentPathButton.setText(_translate("Settings", "浏览"))
